// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjnDjlInoNpd3Kf8hcoatMDNNs6IleeRg',
    appId: '1:585793378017:web:3e6b9afed54a3f641709a0',
    messagingSenderId: '585793378017',
    projectId: 'newswizdb-fc765',
    authDomain: 'newswizdb-fc765.firebaseapp.com',
    storageBucket: 'newswizdb-fc765.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBptpR9Qsagyru1u8tLq6ShCoAcA6o4-JQ',
    appId: '1:585793378017:android:b1f6efbe5d8291a61709a0',
    messagingSenderId: '585793378017',
    projectId: 'newswizdb-fc765',
    storageBucket: 'newswizdb-fc765.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOGSxKThEPKsIgt4goB54Xt2fB_i5BkJw',
    appId: '1:585793378017:ios:82fce63de8cb032d1709a0',
    messagingSenderId: '585793378017',
    projectId: 'newswizdb-fc765',
    storageBucket: 'newswizdb-fc765.appspot.com',
    iosClientId: '585793378017-ql8cjnpfkq4g8p4sr12k19teeov7v437.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsWiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOGSxKThEPKsIgt4goB54Xt2fB_i5BkJw',
    appId: '1:585793378017:ios:82fce63de8cb032d1709a0',
    messagingSenderId: '585793378017',
    projectId: 'newswizdb-fc765',
    storageBucket: 'newswizdb-fc765.appspot.com',
    iosClientId: '585793378017-ql8cjnpfkq4g8p4sr12k19teeov7v437.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsWiz',
  );
}
